django_eb/django_eb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^web_med/', include('web_med.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_eb/web_med/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


app_name = 'web_med'

urlpatterns = [

    # /web_med/
    url(r'^$', views.index, name='index'),

    ############ Authentication System ############
    url(r'^login/$', views.login_view, name = 'login'),
    url(r'^register/$', views.register_view, name = 'register'),
    url(r'^logout/$', views.logout_view, name = 'logout'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.view_profile, name='view_profile_with_pk'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    
    ### Patients

    # /web_med/patients/
    # /web_med/patients/add/
    # /web_med/patients/pk/slug/
    # /web_med/patients/pk/slug/update/
    # /web_med/patients/pk/slug/delete/

    ############ Patient ############
    url(r'^patients/$', views.patients_list, name='patients'),
    url(r'^patients/add/$', views.patientadd, name='patient-add'),
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)$', views.patientdetail, name='patient_detail'),
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/update/$', views.patientupdate, name='patient-update'),    
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/delete/$', views.patientdelete, name='patient-delete'),

    ############ Photo ############
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/progress-bar-upload/$', views.ProgressBarUploadView.as_view(), name='progress_bar_upload'),
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/drag-and-drop-upload/$', views.DragAndDropUploadView.as_view(), name='drag_and_drop_upload'),
   
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/clear/$', views.clear_files, name='clear_files'),

    ############ Nii & VTK ############
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/drag-and-drop-upload-nii/$', views.DragAndDropUploadViewNii.as_view(), name='drag_and_drop_upload_nii'),
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/drag-and-drop-upload-vtk/$', views.DragAndDropUploadViewVTK.as_view(), name='drag_and_drop_upload_vtk'),

    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/clear-nii/$', views.clear_files_nii, name='clear_files_nii'),
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/clear-vtk/$', views.clear_files_vtk, name='clear_files_vtk'),

    ##### Cornerstone Dicom Processing #####
    url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/$', views.dicomprocess, name='dicom-process'),
    
    ## Nii Visualizer 
    url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/Nii$', views.niiprocess, name='nii-process'),
    
    # VTK Visualizer 
    url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/VTK$', views.vtkprocess, name='vtk-process'),
 
    ##### Algorithms #####
    
        ##Filtering
            ##Image Denoising:Linear
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/mean$', views.mean, name='mean'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/median$', views.median, name='median'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/BinomialBlur$', views.BinomialBlur, name='BinomialBlur'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/RecursiveGaussian$', views.RecursiveGaussian, name='RecursiveGaussian'),
            ##Image Denoising:Non-Linear
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/CurvatureAnisotropicDiffusion$', views.CurvatureAnisotropicDiffusion, name='CurvatureAnisotropicDiffusion'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/CurvatureFlow$', views.CurvatureFlow, name='CurvatureFlow'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/GradientAnisotropicDiffusion$', views.GradientAnisotropicDiffusion, name='GradientAnisotropicDiffusion'),
            ##Image Morphology        
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/BinaryDilate$', views.BinaryDilate, name='BinaryDilate'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/BinaryErode$', views.BinaryErode, name='BinaryErode'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/GrayScaleDilate$', views.GrayScaleDilate, name='GrayScaleDilate'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/GrayScaleErode$', views.GrayScaleErode, name='GrayScaleErode'),
            ##Edge Detection & Feature Extraction
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/CannyEdgeDetection$', views.CannyEdgeDetection, name='CannyEdgeDetection'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/SobelEdgeDetection$', views.SobelEdgeDetection, name='SobelEdgeDetection'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/LaplacianRecursive$', views.LaplacianRecursive, name='LaplacianRecursive'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/GradientMagnitude$', views.GradientMagnitude, name='GradientMagnitude'),
            ##Image Intensity Transformations
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/Sigmoid$', views.Sigmoid, name='Sigmoid'),        
        ##Segmentation
            ##Thresholding 
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/BinaryThreshold$', views.BinaryThreshold, name='BinaryThreshold'),        
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/OtsuThreshold$', views.OtsuThreshold, name='OtsuThreshold'),        
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/Threshold$', views.Threshold, name='Threshold'),        
            ##Region Growing
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/ConfidenceConnected$', views.ConfidenceConnected, name='ConfidenceConnected'),        
            ##Watershed
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/Watershed$', views.Watershed, name='Watershed'),        


    ##### SliceDrop #####
    url(r'^patients/process/SliceDrop/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)$', views.SliceDrop, name='SliceDrop'),

    ##### QuadView #####
    url(r'^patients/process/QuadView/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)$', views.QuadView, name='QuadView'),

    ##### AMI Volume Rendering #####
    url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/l15$', views.l15process, name='l15-process'),

    ##### Volume Segmentation #####
    url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/VolumeSegmentation$', views.VolumeSegmentation, name='VolumeSegmentation'),

    ##### Volume Segmentation View #####
    url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/VolumeSegmentationView$', views.vtksegview, name='vtksegview'),   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_eb/web_med/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
import os
import os.path

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name= 'user', primary_key=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.user.username

    def __str__(self):
        return self.first_name
    
    def __str__(self):
        return self.last_name
        

def create_profile(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        user_profile = UserProfile(user=user)
        user_profile.save()
        #user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)


class Patient(models.Model):
    doctor = models.IntegerField(default=1)
    firstName = models.CharField(max_length=200)
    lastName = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.firstName + ' ' + self.lastName + ' - ' + self.description

    def slug(self):
        return slugify(self.lastName)

### Upload to function
def get_upload_to(instance, filename):
    return os.path.join('dicom', str(instance.patient.id), filename)

def get_upload_to_nii(instance, filename):
    return os.path.join('nii', str(instance.patient.id), filename)

def get_upload_to_vtk(instance, filename):
    return os.path.join('vtk', str(instance.patient.id), filename)

class Photo(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient_photos')
    #title = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to=get_upload_to)
    #uploaded_at = models.DateTimeField(auto_now_add=True)

    def get_file_name(self):
        path = self.file.name
        return os.path.basename(path)

    def get_file_name_withoutExtension(self):
        path = self.file.name
        base = os.path.basename(path)
        return os.path.splitext(base)[0]


class Photopng(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient_photos_png')
    image = models.ImageField()

class Nii(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient_niis')
    file = models.FileField(upload_to=get_upload_to_nii)

    def get_file_name(self):
        path = self.file.name
        return os.path.basename(path)

    def get_file_name_withoutExtension(self):
        path = self.file.name
        base = os.path.basename(path)
        return os.path.splitext(base)[0]


class VTK(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient_vtks')
    file = models.FileField(upload_to=get_upload_to_vtk)

    def get_file_name(self):
        path = self.file.name
        return os.path.basename(path)

    def get_file_name_withoutExtension(self):
        path = self.file.name
        base = os.path.basename(path)
        return os.path.splitext(base)[0]

django_eb/web_med/forms.py
from django.contrib.auth import authenticate, get_user_model
from django import forms
from django.contrib.auth.models import User
from .models import Patient, Photo, UserProfile, Nii, VTK
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class PatientForm(forms.ModelForm):
    firstName  = forms.CharField(widget=forms.TextInput(
        attrs={
            'class' : 'form-control',
        }
    ))

    lastName  = forms.CharField(widget=forms.TextInput(
        attrs={
            'class' : 'form-control',
        }
    ))

    description  = forms.CharField(widget=forms.Textarea(
        attrs={
            'class' : 'form-control',
        }
    ))

    class Meta:
        model = Patient
        fields = ('firstName', 'lastName', 'description')

class PhotoForm(forms.ModelForm):

    class Meta:
        model = Photo
        fields = ('file', )

class NiiForm(forms.ModelForm):
    
    class Meta:
        model = Nii
        fields = ('file', )

class VTKForm(forms.ModelForm):
    
    class Meta:
        model = VTK
        fields = ('file', )

class UsersLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput,)

    def __init__(self, *args, **kwargs):
        super(UsersLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            "name":"username"})
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            "name":"password"})

    def clean(self, *args, **keyargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user does not exists")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect Password")
            if not user.is_active:
                raise forms.ValidationError("User is no longer active")

        return super(UsersLoginForm, self).clean(*args, **keyargs)


User = get_user_model()

class UsersRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "confirm_email", 
            "password"
        ]
    username = forms.CharField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField(label="Email")
    confirm_email = forms.EmailField(label="Confirm Email")
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(UsersRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            "name":"username"})
        self.fields['first_name'].widget.attrs.update({
            'class': 'form-control',
            "name":"first_name"})
        self.fields['last_name'].widget.attrs.update({
            'class': 'form-control',
            "name":"last_name"})
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            "name":"email"})
        self.fields['confirm_email'].widget.attrs.update({
            'class': 'form-control',
            "name":"confirm_email"})
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            "name":"password"})

    def clean(self, *args, **keyargs):
        email = self.cleaned_data.get("email")
        confirm_email = self.cleaned_data.get("confirm_email")
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")

        if email != confirm_email:
            raise forms.ValidationError("Email must match")
        
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("Email is already registered")

        username_qs = User.objects.filter(username=username)
        if username_qs.exists():
            raise forms.ValidationError("User with this username already registered")

        if len(password) < 6:	#you can add more validations for password
            raise forms.ValidationError("Password must be greater than 6 characters")

        return super(UsersRegisterForm, self).clean(*args, **keyargs)

class EditProfileForm(UserChangeForm):
    template_name='/something/else'

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password', 
        )

django_eb/web_med/templates/web_med/progress_bar_upload/index.html
{% extends 'web_med/detail.html' %} {% load static %} {% block title %}Progress Bar Upload{% endblock %} {% block javascript %} {# JQUERY FILE UPLOAD SCRIPTS #}
<script src="{% static 'web_med/js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
<script src="{% static 'web_med/js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
<script src="{% static 'web_med/js/jquery-file-upload/jquery.fileupload.js' %}"></script>

{# PHOTOS PAGE SCRIPTS #}
<script src="{% static 'web_med/js/progress-bar-upload.js' %}"></script>
<script type="text/javascript" src="{% static 'web_med/js/extra.js' %}"></script>

{% endblock %} {% block photos_contentsss %}
<meta name="viewport" content="width=device-width, initial-scale=1">

<div style="margin-bottom: 20px;">
    <button type="button" class="btn btn-primary js-upload-photos">
      <span class="glyphicon glyphicon-cloud-upload"></span> Upload Dicom Files
    </button>
    <input id="fileupload" type="file" name="file" multiple onchange="getfiles(this.files)" style="display: none;" data-url="{% url 'web_med:progress_bar_upload' pi ps %}" data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
</div>

<p style="font-size: 1.8rem;">
    <b><u>Uploaded Files:</u></b>
</p>
<br>
<p>
    <a href="{% url 'web_med:SliceDrop' pi ps %}">SliceDrop</a>
</p>
<p>
    <a href="{% url 'web_med:l15-process' pi ps %}">
        <button type="button" class="btn btn-success" style="font-size:20px">View Rendered 3D Volume</button>
    </a>
</p>
<p>
    <button type="button" class="btn btn-success" style="font-size:20px" id="VolumeSeg" data-toggle="modal" data-target="#VTKSeg">Volume Segmentation</button>
</p>

<!-- Image loader -->
<div id="loader" class="overlay" style="display:none">
    <div id="spinner">
    </div>
</div>

<form method="post" action="{% url 'web_med:clear_files' pi ps %}">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.path }}">
    <button type="submit" class="btn btn-danger pull-right">
        <span class="glyphicon glyphicon-trash"></span> Clear All Dicom Files
    </button>
</form>

<table id="gallery" class="table table-bordered">
    <tbody>
        {% for photo in photos %}
        <tr>
            <td style="font-size: 2rem">
                {{ photo.get_file_name }}
            </td>
            <td>
                <button type=" button" class="openImageDialog btn btn-primary btn-lg" data-id="/media/png/{{pi}}/{{photo.get_file_name_withoutExtension}}.png" data-toggle="modal" href="#myModal">Quick View</button>

                <!-- Modal -->
                <div class="modal fade" id="myModal" role="dialog">
                    <div class="modal-dialog" role="document">
                        <!-- Modal Content -->
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title"><b>Quick View</b></h4>
                            </div>
                            <div class="modal-body">
                                <img id="myImage" class="img-responsive" src=" " alt style="width:700px;">
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>

                        </div>
                    </div>
                </div>
                <script>
                    $(document).on("click", ".openImageDialog", function() {
                        console.log('Ok');
                    });

                    $(document).on("click", ".openImageDialog", function() {
                        var myImageId = $(this).data('id');
                    });

                    $(document).on("click", ".openImageDialog", function() {
                        var myImageId = $(this).data('id');
                        $(".modal-body #myImage").attr("src", myImageId);
                    });
                </script>


            </td>
            <td>
                <a class="btn btn-warning btn-lg" href="{% url 'web_med:dicom-process' pk=pi slug=ps name=photo.get_file_name_withoutExtension %}">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Uploading...</h4>
            </div>
            <div class="modal-body">
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="VTKSeg" tabindex="-1" role="dialog" aria-labelledby="Volume Segmentation" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title" title="Threshold based on the Hounsfield scale of tissue density&#10;-1000 to +1000HU&#10;Air:  -1000 HU&#10;Water:  0 HU" data-toggle="tooltip">Volume Segmentation</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST">
                <div class="modal-body">
                    {% csrf_token %}
                    <label for="">Lower Threshold:&nbsp;</label>
                    <input type="text" id="LowerThreshold" size="10">
                    <br><br>
                    <label for="">Upper Threshold:&nbsp;</label>
                    <input type="text" id="UpperThreshold" size="10">
                    <br><br>
                    <label for="">Name:&nbsp;</label>
                    <input type="text" id="Name" size="10" value="">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-warning" onclick="VolumeSegmentation()">Apply</button>
                    <button type="button" class="btn btn-primary" onclick="VTKSegView()">View</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    function VTKSegView() {
        window.open("{% url 'web_med:vtksegview' pk=pi slug=ps %}", "_blank");
        $('#VTKSeg').modal('toggle');

    }

    function VolumeSegmentation() {

        $.ajax({
            type: "POST",
            url: "{% url 'web_med:VolumeSegmentation' pi ps %}",
            async: true,
            data: {
                csrfmiddlewaretoken: '{{ csrf_token }}',
                LowerThreshold: $('#LowerThreshold').val(),
                UpperThreshold: $('#UpperThreshold').val(),
                Name: $('#Name').val()
            },
            beforeSend: function() {
                $('#loader').show();
                $('#VTKSeg').hide();
            },
            success: function() {
                $('#loader').hide();
                $('#VTKSeg').show();
            }
        });
    }
</script>
<style>
    .modal-dialog {
        min-height: calc(100vh - 60px);
        display: flex;
        flex-direction: column;
        justify-content: center;
        overflow: auto;
    }
    
    @media(max-width: 768px) {
        .modal-dialog {
            min-height: calc(100vh - 20px);
        }
    }
    
    .overlay {
        height: 100%;
        width: 100%;
        display: none;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
        background-color: rgb(0, 0, 0);
        background-color: rgba(0, 0, 0, 0.8);
    }
    
    .overlay-content {
        position: relative;
        top: 25%;
        width: 100%;
        text-align: center;
        margin-top: 30px;
    }
    
    @media screen and (max-height: 450px) {
        .overlay a {
            font-size: 20px
        }
        .overlay .closebtn {
            font-size: 40px;
            top: 15px;
            right: 35px;
        }
    }
    
    #spinner {
        position: absolute;
        left: 50%;
        top: 50%;
        z-index: 1;
        width: 150px;
        height: 150px;
        margin: -75px 0 0 -75px;
        border: 16px solid #f3f3f3;
        border-radius: 50%;
        border-top: 16px solid #3498db;
        width: 120px;
        height: 120px;
        -webkit-animation: spin 2s linear infinite;
        animation: spin 2s linear infinite;
    }
    
    @-webkit-keyframes spin {
        0% {
            -webkit-transform: rotate(0deg);
        }
        100% {
            -webkit-transform: rotate(360deg);
        }
    }
    
    @keyframes spin {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }
</style>
{% endblock %}