django_eb/django_eb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^web_med/', include('web_med.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_eb/web_med/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


app_name = 'web_med'

urlpatterns = [

    # /web_med/
    url(r'^$', views.index, name='index'),

    ############ Authentication System ############
    url(r'^login/$', views.login_view, name = 'login'),
    url(r'^register/$', views.register_view, name = 'register'),
    url(r'^logout/$', views.logout_view, name = 'logout'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.view_profile, name='view_profile_with_pk'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    
    ### Patients

    # /web_med/patients/
    # /web_med/patients/add/
    # /web_med/patients/pk/slug/
    # /web_med/patients/pk/slug/update/
    # /web_med/patients/pk/slug/delete/

    ############ Patient ############
    url(r'^patients/$', views.patients_list, name='patients'),
    url(r'^patients/add/$', views.patientadd, name='patient-add'),
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)$', views.patientdetail, name='patient_detail'),
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/update/$', views.patientupdate, name='patient-update'),    
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/delete/$', views.patientdelete, name='patient-delete'),

    ############ Photo ############
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/progress-bar-upload/$', views.ProgressBarUploadView.as_view(), name='progress_bar_upload'),
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/drag-and-drop-upload/$', views.DragAndDropUploadView.as_view(), name='drag_and_drop_upload'),
   
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/clear/$', views.clear_files, name='clear_files'),

    ############ Nii & VTK ############
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/drag-and-drop-upload-nii/$', views.DragAndDropUploadViewNii.as_view(), name='drag_and_drop_upload_nii'),
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/drag-and-drop-upload-vtk/$', views.DragAndDropUploadViewVTK.as_view(), name='drag_and_drop_upload_vtk'),

    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/clear-nii/$', views.clear_files_nii, name='clear_files_nii'),
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/clear-vtk/$', views.clear_files_vtk, name='clear_files_vtk'),

    ##### Cornerstone Dicom Processing #####
    url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/$', views.dicomprocess, name='dicom-process'),
    
    ## Nii Visualizer 
    url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/Nii$', views.niiprocess, name='nii-process'),
    
    # VTK Visualizer 
    url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/VTK$', views.vtkprocess, name='vtk-process'),
 
    ##### Algorithms #####
    
        ##Filtering
            ##Image Denoising:Linear
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/mean$', views.mean, name='mean'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/median$', views.median, name='median'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/BinomialBlur$', views.BinomialBlur, name='BinomialBlur'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/RecursiveGaussian$', views.RecursiveGaussian, name='RecursiveGaussian'),
            ##Image Denoising:Non-Linear
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/CurvatureAnisotropicDiffusion$', views.CurvatureAnisotropicDiffusion, name='CurvatureAnisotropicDiffusion'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/CurvatureFlow$', views.CurvatureFlow, name='CurvatureFlow'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/GradientAnisotropicDiffusion$', views.GradientAnisotropicDiffusion, name='GradientAnisotropicDiffusion'),
            ##Image Morphology        
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/BinaryDilate$', views.BinaryDilate, name='BinaryDilate'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/BinaryErode$', views.BinaryErode, name='BinaryErode'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/GrayScaleDilate$', views.GrayScaleDilate, name='GrayScaleDilate'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/GrayScaleErode$', views.GrayScaleErode, name='GrayScaleErode'),
            ##Edge Detection & Feature Extraction
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/CannyEdgeDetection$', views.CannyEdgeDetection, name='CannyEdgeDetection'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/SobelEdgeDetection$', views.SobelEdgeDetection, name='SobelEdgeDetection'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/LaplacianRecursive$', views.LaplacianRecursive, name='LaplacianRecursive'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/GradientMagnitude$', views.GradientMagnitude, name='GradientMagnitude'),
            ##Image Intensity Transformations
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/Sigmoid$', views.Sigmoid, name='Sigmoid'),        
        ##Segmentation
            ##Thresholding 
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/BinaryThreshold$', views.BinaryThreshold, name='BinaryThreshold'),        
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/OtsuThreshold$', views.OtsuThreshold, name='OtsuThreshold'),        
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/Threshold$', views.Threshold, name='Threshold'),        
            ##Region Growing
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/ConfidenceConnected$', views.ConfidenceConnected, name='ConfidenceConnected'),        
            ##Watershed
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/Watershed$', views.Watershed, name='Watershed'),        


    ##### SliceDrop #####
    url(r'^patients/process/SliceDrop/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)$', views.SliceDrop, name='SliceDrop'),

    ##### QuadView #####
    url(r'^patients/process/QuadView/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)$', views.QuadView, name='QuadView'),

    ##### AMI Volume Rendering #####
    url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/l15$', views.l15process, name='l15-process'),

    ##### Volume Segmentation #####
    url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/VolumeSegmentation$', views.VolumeSegmentation, name='VolumeSegmentation'),

    ##### Volume Segmentation View #####
    url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/VolumeSegmentationView$', views.vtksegview, name='vtksegview'),   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_eb/web_med/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
import os
import os.path

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name= 'user', primary_key=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.user.username

    def __str__(self):
        return self.first_name
    
    def __str__(self):
        return self.last_name
        

def create_profile(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        user_profile = UserProfile(user=user)
        user_profile.save()
        #user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)


class Patient(models.Model):
    doctor = models.IntegerField(default=1)
    firstName = models.CharField(max_length=200)
    lastName = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.firstName + ' ' + self.lastName + ' - ' + self.description

    def slug(self):
        return slugify(self.lastName)

### Upload to function
def get_upload_to(instance, filename):
    return os.path.join('dicom', str(instance.patient.id), filename)

def get_upload_to_nii(instance, filename):
    return os.path.join('nii', str(instance.patient.id), filename)

def get_upload_to_vtk(instance, filename):
    return os.path.join('vtk', str(instance.patient.id), filename)

class Photo(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient_photos')
    #title = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to=get_upload_to)
    #uploaded_at = models.DateTimeField(auto_now_add=True)

    def get_file_name(self):
        path = self.file.name
        return os.path.basename(path)

    def get_file_name_withoutExtension(self):
        path = self.file.name
        base = os.path.basename(path)
        return os.path.splitext(base)[0]


class Photopng(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient_photos_png')
    image = models.ImageField()

class Nii(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient_niis')
    file = models.FileField(upload_to=get_upload_to_nii)

    def get_file_name(self):
        path = self.file.name
        return os.path.basename(path)

    def get_file_name_withoutExtension(self):
        path = self.file.name
        base = os.path.basename(path)
        return os.path.splitext(base)[0]


class VTK(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient_vtks')
    file = models.FileField(upload_to=get_upload_to_vtk)

    def get_file_name(self):
        path = self.file.name
        return os.path.basename(path)

    def get_file_name_withoutExtension(self):
        path = self.file.name
        base = os.path.basename(path)
        return os.path.splitext(base)[0]

django_eb/web_med/forms.py
from django.contrib.auth import authenticate, get_user_model
from django import forms
from django.contrib.auth.models import User
from .models import Patient, Photo, UserProfile, Nii, VTK
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class PatientForm(forms.ModelForm):
    firstName  = forms.CharField(widget=forms.TextInput(
        attrs={
            'class' : 'form-control',
        }
    ))

    lastName  = forms.CharField(widget=forms.TextInput(
        attrs={
            'class' : 'form-control',
        }
    ))

    description  = forms.CharField(widget=forms.Textarea(
        attrs={
            'class' : 'form-control',
        }
    ))

    class Meta:
        model = Patient
        fields = ('firstName', 'lastName', 'description')

class PhotoForm(forms.ModelForm):

    class Meta:
        model = Photo
        fields = ('file', )

class NiiForm(forms.ModelForm):
    
    class Meta:
        model = Nii
        fields = ('file', )

class VTKForm(forms.ModelForm):
    
    class Meta:
        model = VTK
        fields = ('file', )

class UsersLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput,)

    def __init__(self, *args, **kwargs):
        super(UsersLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            "name":"username"})
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            "name":"password"})

    def clean(self, *args, **keyargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user does not exists")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect Password")
            if not user.is_active:
                raise forms.ValidationError("User is no longer active")

        return super(UsersLoginForm, self).clean(*args, **keyargs)


User = get_user_model()

class UsersRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "confirm_email", 
            "password"
        ]
    username = forms.CharField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField(label="Email")
    confirm_email = forms.EmailField(label="Confirm Email")
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(UsersRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            "name":"username"})
        self.fields['first_name'].widget.attrs.update({
            'class': 'form-control',
            "name":"first_name"})
        self.fields['last_name'].widget.attrs.update({
            'class': 'form-control',
            "name":"last_name"})
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            "name":"email"})
        self.fields['confirm_email'].widget.attrs.update({
            'class': 'form-control',
            "name":"confirm_email"})
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            "name":"password"})

    def clean(self, *args, **keyargs):
        email = self.cleaned_data.get("email")
        confirm_email = self.cleaned_data.get("confirm_email")
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")

        if email != confirm_email:
            raise forms.ValidationError("Email must match")
        
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("Email is already registered")

        username_qs = User.objects.filter(username=username)
        if username_qs.exists():
            raise forms.ValidationError("User with this username already registered")

        if len(password) < 6:	#you can add more validations for password
            raise forms.ValidationError("Password must be greater than 6 characters")

        return super(UsersRegisterForm, self).clean(*args, **keyargs)

class EditProfileForm(UserChangeForm):
    template_name='/something/else'

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password', 
        )

django_eb/web_med/templates/web_med/edit_profile.html
{% extends 'web_med/userBase.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form class="form-signin" method="POST" action="" enctype="multipart/form-data" style="margin-top: -30px; margin-bottom: -18px;">{% csrf_token %}
        <h2 class="form-signin-heading">{{title}}</h2>
        {{form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

django_eb/web_med/templates/web_med/form.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Login{% endblock %}</title>

    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'web_med/patientsstyle.css' %}" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Junction">

    <script src="{% static 'web_med/js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'web_med/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'web_med/js/es6-promise.min.js' %}"></script>

</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!--Header-->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'web_med:index' %}">
                    <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;HomePage
                </a>
            </div>

        </div>
    </nav>

    <div class="container">
        <div class="col-md-6 col-md-offset-3">
            <div class="wrapper">
                <form class="form-signin" method="POST" action="" enctype="multipart/form-data" style="margin-top: -30px; margin-bottom: -18px;">{% csrf_token %}
                    <h2 class="form-signin-heading">{{title}}</h2>
                    {{form.as_p }}
                    <br>
                    <button class="btn btn-lg btn-primary btn-block" type="submit">{{title}}</button>
                    <br> {% if title == "Login" %}
                    <h5>Not Registered? <a href="/web_med/register">Register Here</a></h5>{% endif %} {% if title == "Register" %}
                    <h5>Already Registered? <a href="/web_med/login">Login Here</a></h5>{% endif %}
                </form>
            </div>
        </div>
    </div>
    <style type="text/css">
    .wrapper {
            margin-top: 80px;
            margin-bottom: 80px;
        }
        
        .form-signin {
            padding: 15px 35px 45px;
            margin: 0 auto;
            background-color: #fff;
            border: 1px solid rgba(0, 0, 0, 0.1);
        }
        
        .form-signin-heading,
        .checkbox {
            margin-bottom: 30px;
        }
        
        .checkbox {
            font-weight: normal;
        }
        
        .form-control {
            position: relative;
            font-size: 16px;
            height: auto;
            padding: 10px;
        }
        
        input[type="text"] {
            margin-bottom: -1px;
            border-bottom-left-radius: 0;
            border-bottom-right-radius: 0;
        }
        
        input[type="password"] {
            margin-bottom: 20px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    }
    @media(max-width: 500px) {
        footer {
            height: 130px !important;
            padding-bottom: 10px;
            padding-top: 10px;
        }
    }
    </style>
</body>

</html>

django_eb/web_med/templates/web_med/mainpage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Web-Based Medical Image Processing</title>

    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!--<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Junction">-->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Raleway:400,300,600">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <style>
        body {
            font-family: "Raleway", "HelveticaNeue", "Helvetica Neue", Helvetica, Arial, sans-serif;
            line-height: 2;
        }
        
        p {
            font-size: 16px;
            color: black;
        }
        
        .navbar {
            padding-top: 10px;
            padding-bottom: 10px;
            border: 0;
            border-radius: 0;
            margin-bottom: 0;
            font-size: 18px;
            letter-spacing: 5px;
        }
        
        .navbar-nav li a:hover {
            color: #1abc9c !important;
        }
        
        .value-img {
            margin-bottom: 1rem;
        }
        
        .value-props {
            margin-top: 9rem;
            margin-bottom: 7rem;
        }
        
        strong {
            font-weight: bold;
        }
        
        h2 {
            font-size: 4.2rem;
            display: block;
            -webkit-margin-before: 0.83em;
            -webkit-margin-after: 0.83em;
            -webkit-margin-start: 0px;
            -webkit-margin-end: 0px;
            margin-top: 0;
            margin-bottom: 2rem;
            font-weight: 300;
            line-height: 1.25;
            letter-spacing: -.1rem;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!--Header-->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle " data-toggle="collapse" data-target="#myNavbar ">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a style="color:white" class="navbar-brand " href="{% url 'web_med:index' %} ">
                    Web-Med
                </a>
            </div>

            <!--Items -->
            <div class="collapse navbar-collapse " id="myNavbar">
                <ul class=" nav navbar-nav navbar-right ">
                    <li class=""><a style="color:white" href="{% url 'web_med:login' %} ">Log In</a></li>
                    <li class=""><a style="color:white" href="{% url 'web_med:register' %} ">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" style="max-width:800px;color:black;">
        <section class="header " style="margin-top:6rem;text-align:center;">

            <h2 class="title"><img src="{% static 'web_med/images/web-med-logo.png' %}" width="500" style="max-width:90%">
                <br><br>Web-Based Medical Image Processing
            </h2>
            <div class="row value-props">
                <div class="col-sm-4">
                    <img class="value-img" src="{% static 'web_med/images/circle.png' %}" width="40 ">
                    <p>Upload and Visualize Dicom/Nifti/VTK Files</p>
                </div>
                <div class="col-sm-4">
                    <img class="value-img" src="{% static 'web_med/images/circle.png' %}" width="40 ">
                    <p>Measurement and Annotation Tools</p>
                </div>
                <div class="col-sm-4">
                    <img class="value-img" src="{% static 'web_med/images/circle.png' %}" width="40 ">
                    <p>Pre-Processing and Segmentation Tools</p>
                </div>
            </div>
        </section>
    </div>

</body>

</html>

django_eb/web_med/templates/web_med/userBase.html
{% load static %}
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Base</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Junction">
    <link rel="stylesheet" type="text/css" href="{% static 'web_med/patientsstyle.css' %}" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% block head %}
    <title>Base</title>
    {% endblock %}
</head>

<body>
    <br>
    <div class="container">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                    <a class="navbar-brand" href="{% url 'web_med:index' %}">WebMed</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    {% if user.is_authenticated %}
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'web_med:view_profile' %}">Profile</a></li>
                        <li><a href="{% url 'web_med:edit_profile' %}">Edit Profile</a></li>
                        <li><a href="{% url 'web_med:patients' %}">Patients</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'web_med:logout' %}">Log out</a></li>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </nav>
    </div>
    {% block body %}
    <h1>Base</h1>
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</html>