django_eb/django_eb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^web_med/', include('web_med.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_eb/web_med/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


app_name = 'web_med'

urlpatterns = [

    # /web_med/
    url(r'^$', views.index, name='index'),

    ############ Authentication System ############
    url(r'^login/$', views.login_view, name = 'login'),
    url(r'^register/$', views.register_view, name = 'register'),
    url(r'^logout/$', views.logout_view, name = 'logout'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.view_profile, name='view_profile_with_pk'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    
    ### Patients

    # /web_med/patients/
    # /web_med/patients/add/
    # /web_med/patients/pk/slug/
    # /web_med/patients/pk/slug/update/
    # /web_med/patients/pk/slug/delete/

    ############ Patient ############
    url(r'^patients/$', views.patients_list, name='patients'),
    url(r'^patients/add/$', views.patientadd, name='patient-add'),
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)$', views.patientdetail, name='patient_detail'),
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/update/$', views.patientupdate, name='patient-update'),    
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/delete/$', views.patientdelete, name='patient-delete'),

    ############ Photo ############
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/progress-bar-upload/$', views.ProgressBarUploadView.as_view(), name='progress_bar_upload'),
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/drag-and-drop-upload/$', views.DragAndDropUploadView.as_view(), name='drag_and_drop_upload'),
   
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/clear/$', views.clear_files, name='clear_files'),

    ############ Nii & VTK ############
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/drag-and-drop-upload-nii/$', views.DragAndDropUploadViewNii.as_view(), name='drag_and_drop_upload_nii'),
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/drag-and-drop-upload-vtk/$', views.DragAndDropUploadViewVTK.as_view(), name='drag_and_drop_upload_vtk'),

    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/clear-nii/$', views.clear_files_nii, name='clear_files_nii'),
    url(r'^patients/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/clear-vtk/$', views.clear_files_vtk, name='clear_files_vtk'),

    ##### Cornerstone Dicom Processing #####
    url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/$', views.dicomprocess, name='dicom-process'),
    
    ## Nii Visualizer 
    url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/Nii$', views.niiprocess, name='nii-process'),
    
    # VTK Visualizer 
    url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/VTK$', views.vtkprocess, name='vtk-process'),
 
    ##### Algorithms #####
    
        ##Filtering
            ##Image Denoising:Linear
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/mean$', views.mean, name='mean'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/median$', views.median, name='median'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/BinomialBlur$', views.BinomialBlur, name='BinomialBlur'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/RecursiveGaussian$', views.RecursiveGaussian, name='RecursiveGaussian'),
            ##Image Denoising:Non-Linear
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/CurvatureAnisotropicDiffusion$', views.CurvatureAnisotropicDiffusion, name='CurvatureAnisotropicDiffusion'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/CurvatureFlow$', views.CurvatureFlow, name='CurvatureFlow'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/GradientAnisotropicDiffusion$', views.GradientAnisotropicDiffusion, name='GradientAnisotropicDiffusion'),
            ##Image Morphology        
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/BinaryDilate$', views.BinaryDilate, name='BinaryDilate'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/BinaryErode$', views.BinaryErode, name='BinaryErode'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/GrayScaleDilate$', views.GrayScaleDilate, name='GrayScaleDilate'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/GrayScaleErode$', views.GrayScaleErode, name='GrayScaleErode'),
            ##Edge Detection & Feature Extraction
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/CannyEdgeDetection$', views.CannyEdgeDetection, name='CannyEdgeDetection'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/SobelEdgeDetection$', views.SobelEdgeDetection, name='SobelEdgeDetection'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/LaplacianRecursive$', views.LaplacianRecursive, name='LaplacianRecursive'),
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/GradientMagnitude$', views.GradientMagnitude, name='GradientMagnitude'),
            ##Image Intensity Transformations
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/Sigmoid$', views.Sigmoid, name='Sigmoid'),        
        ##Segmentation
            ##Thresholding 
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/BinaryThreshold$', views.BinaryThreshold, name='BinaryThreshold'),        
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/OtsuThreshold$', views.OtsuThreshold, name='OtsuThreshold'),        
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/Threshold$', views.Threshold, name='Threshold'),        
            ##Region Growing
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/ConfidenceConnected$', views.ConfidenceConnected, name='ConfidenceConnected'),        
            ##Watershed
            url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<name>[\w\W.]+)/Watershed$', views.Watershed, name='Watershed'),        


    ##### SliceDrop #####
    url(r'^patients/process/SliceDrop/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)$', views.SliceDrop, name='SliceDrop'),

    ##### QuadView #####
    url(r'^patients/process/QuadView/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)$', views.QuadView, name='QuadView'),

    ##### AMI Volume Rendering #####
    url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/l15$', views.l15process, name='l15-process'),

    ##### Volume Segmentation #####
    url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/VolumeSegmentation$', views.VolumeSegmentation, name='VolumeSegmentation'),

    ##### Volume Segmentation View #####
    url(r'^patients/process/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/VolumeSegmentationView$', views.vtksegview, name='vtksegview'),   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_eb/web_med/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
import os
import os.path

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name= 'user', primary_key=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.user.username

    def __str__(self):
        return self.first_name
    
    def __str__(self):
        return self.last_name
        

def create_profile(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        user_profile = UserProfile(user=user)
        user_profile.save()
        #user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)


class Patient(models.Model):
    doctor = models.IntegerField(default=1)
    firstName = models.CharField(max_length=200)
    lastName = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.firstName + ' ' + self.lastName + ' - ' + self.description

    def slug(self):
        return slugify(self.lastName)

### Upload to function
def get_upload_to(instance, filename):
    return os.path.join('dicom', str(instance.patient.id), filename)

def get_upload_to_nii(instance, filename):
    return os.path.join('nii', str(instance.patient.id), filename)

def get_upload_to_vtk(instance, filename):
    return os.path.join('vtk', str(instance.patient.id), filename)

class Photo(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient_photos')
    #title = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to=get_upload_to)
    #uploaded_at = models.DateTimeField(auto_now_add=True)

    def get_file_name(self):
        path = self.file.name
        return os.path.basename(path)

    def get_file_name_withoutExtension(self):
        path = self.file.name
        base = os.path.basename(path)
        return os.path.splitext(base)[0]


class Photopng(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient_photos_png')
    image = models.ImageField()

class Nii(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient_niis')
    file = models.FileField(upload_to=get_upload_to_nii)

    def get_file_name(self):
        path = self.file.name
        return os.path.basename(path)

    def get_file_name_withoutExtension(self):
        path = self.file.name
        base = os.path.basename(path)
        return os.path.splitext(base)[0]


class VTK(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient_vtks')
    file = models.FileField(upload_to=get_upload_to_vtk)

    def get_file_name(self):
        path = self.file.name
        return os.path.basename(path)

    def get_file_name_withoutExtension(self):
        path = self.file.name
        base = os.path.basename(path)
        return os.path.splitext(base)[0]

django_eb/web_med/forms.py
from django.contrib.auth import authenticate, get_user_model
from django import forms
from django.contrib.auth.models import User
from .models import Patient, Photo, UserProfile, Nii, VTK
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class PatientForm(forms.ModelForm):
    firstName  = forms.CharField(widget=forms.TextInput(
        attrs={
            'class' : 'form-control',
        }
    ))

    lastName  = forms.CharField(widget=forms.TextInput(
        attrs={
            'class' : 'form-control',
        }
    ))

    description  = forms.CharField(widget=forms.Textarea(
        attrs={
            'class' : 'form-control',
        }
    ))

    class Meta:
        model = Patient
        fields = ('firstName', 'lastName', 'description')

class PhotoForm(forms.ModelForm):

    class Meta:
        model = Photo
        fields = ('file', )

class NiiForm(forms.ModelForm):
    
    class Meta:
        model = Nii
        fields = ('file', )

class VTKForm(forms.ModelForm):
    
    class Meta:
        model = VTK
        fields = ('file', )

class UsersLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput,)

    def __init__(self, *args, **kwargs):
        super(UsersLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            "name":"username"})
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            "name":"password"})

    def clean(self, *args, **keyargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user does not exists")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect Password")
            if not user.is_active:
                raise forms.ValidationError("User is no longer active")

        return super(UsersLoginForm, self).clean(*args, **keyargs)


User = get_user_model()

class UsersRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "confirm_email", 
            "password"
        ]
    username = forms.CharField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField(label="Email")
    confirm_email = forms.EmailField(label="Confirm Email")
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(UsersRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            "name":"username"})
        self.fields['first_name'].widget.attrs.update({
            'class': 'form-control',
            "name":"first_name"})
        self.fields['last_name'].widget.attrs.update({
            'class': 'form-control',
            "name":"last_name"})
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            "name":"email"})
        self.fields['confirm_email'].widget.attrs.update({
            'class': 'form-control',
            "name":"confirm_email"})
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            "name":"password"})

    def clean(self, *args, **keyargs):
        email = self.cleaned_data.get("email")
        confirm_email = self.cleaned_data.get("confirm_email")
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")

        if email != confirm_email:
            raise forms.ValidationError("Email must match")
        
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("Email is already registered")

        username_qs = User.objects.filter(username=username)
        if username_qs.exists():
            raise forms.ValidationError("User with this username already registered")

        if len(password) < 6:	#you can add more validations for password
            raise forms.ValidationError("Password must be greater than 6 characters")

        return super(UsersRegisterForm, self).clean(*args, **keyargs)

class EditProfileForm(UserChangeForm):
    template_name='/something/else'

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password', 
        )

django_eb/web_med/templates/web_med/includes/partial_patient_create.html
{% load widget_tweaks %}

<form method="post" action="{% url 'web_med:patient-add' %}" class="js-patient-create-form"> {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Create a new patient</h4>
    </div>
    <div class="modal-body">
        {% include 'web_med/includes/partial_patient_form.html' %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Create Patient</button>
    </div>
</form>

django_eb/web_med/templates/web_med/includes/partial_patient_delete.html
<form method="post" action="{% url 'web_med:patient-delete' patient.id patient.slug %}" class="js-patient-delete-form">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        <h4 class="modal-title">Confirm Patient deletion</h4>
    </div>
    <div class="modal-body">
        <p class="lead">Are you sure you want to delete Patient: <strong>{{ patient.firstName}}&nbsp;{{patient.lastName }}</strong>?</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-danger">Delete Patient</button>
    </div>
</form>

django_eb/web_med/templates/web_med/includes/partial_patient_form.html
{% load widget_tweaks %} {% for field in form %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label> {% render_field field class="form-control" %} {% for error in field.errors %}
    <p class="help-block">{{ error }}</p>
    {% endfor %}
</div>
{% endfor %}

django_eb/web_med/templates/web_med/includes/partial_patient_update.html
<form method="post" action="{% url 'web_med:patient-update' form.instance.pk form.instance.slug %}" class="js-patient-update-form">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Update Patient</h4>
    </div>
    <div class="modal-body">
        {% include 'web_med/includes/partial_patient_form.html' %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Update Patient</button>
    </div>
</form>

django_eb/web_med/templates/web_med/includes/partial_patients_list.html
{% for patient in patients %}
<tr>
    <td style="font-size: 2rem;"><a href="{% url 'web_med:patient_detail' patient.id patient.slug %}">{{ patient.firstName }}</a></td>
    <td style="font-size: 2rem;"><a href="{% url 'web_med:patient_detail' patient.id patient.slug %}">{{ patient.lastName }}</a></td>
    <td style="font-size: 2rem;"><a href="{% url 'web_med:patient_detail' patient.id patient.slug %}">{{ patient.description }}</a></td>

    <td>
        <!-- Update Patient -->
        <button type="button" class="btn btn-warning btn-sm js-update-patient" data-url="{% url 'web_med:patient-update' patient.id patient.slug %}">
            <span class="glyphicon glyphicon-pencil"></span> Edit
        </button>
    </td>
    <td>
        <!-- Delete Patient -->
        <button type="button" class="btn btn-danger btn-sm js-delete-patient" data-url="{% url 'web_med:patient-delete' patient.id patient.slug %}">
            <span class="glyphicon glyphicon-trash"></span> Delete
        </button>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan="8" class="text-center bg-warning">No Patients</td>
</tr>
{% endfor %}
<style>
    a {
        color: inherit;
    }
</style>